[package]
name = "rustychat-client"
version = "0.1.0"
authors = ["Declan Hopkins <hopkins.declan@gmail.com>"]

[dependencies]
gfx = { path = "gfx-lib" }
doosknet = { path = "../doosknet-lib" }
mio = "0.6"
rand = "0.4.2"