[package]
name = "packets"
version = "0.1.0"
authors = ["Declan Hopkins <hopkins.declan@gmail.com>"]

[dependencies]
gfx = { path = "gfx-lib" }
mio = "0.6"
bytes = "0.4"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/main.rs"